### ISSUE TITLE
能出详细一点的文档支持吗？

### ISSUE THREAD

**Issue by lin1123** [jarvis2f/vortex#3]

**Comment by jarvis2f** [comment]
https://github.com/jarvis2f/vortex/blob/ae61f3448dcaa0315d8fa002d09255ce3c070e4d/doc/install.md

**Comment by lin1123** [comment]
> https://github.com/jarvis2f/vortex/blob/ae61f3448dcaa0315d8fa002d09255ce3c070e4d/doc/install.md

看过，太简陋了，不知道哪些必填，那些可以不用，试着docker安装文档安装，启动之后访问不了，日志显示无法访问5432端口。

**Comment by jarvis2f** [comment]
不必填的都有说明。你贴个 docker-compose.yml 和 .env 帮你看看

**Comment by lin1123** [comment]
.env
<
# Prisma
# https://www.prisma.io/docs/reference/database-reference/connection-urls#env
# postgresql://USER:PASSWORD@HOST:PORT/DATABASE
DATABASE_URL="postgresql://postgres:123456@vortex-postgres:5432/vortex"
# If you use docker-compose, you should use the following configuration
POSTGRES_USER="postgres"
POSTGRES_PASSWORD="123456"
POSTGRES_DB="vortex"

# Next Auth
# You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
NEXTAUTH_SECRET="19QjyGKq2qt23unNname0ybG9C2cHQPAOjS8nr4J6Fw="
NEXTAUTH_URL="https://域名"

# Next Auth Providers
# Next Auth GitHub Provider
# GITHUB_CLIENT_ID=""
# GITHUB_CLIENT_SECRET=""

# Next Auth Google Provider
# GOOGLE_CLIENT_ID=""
# GOOGLE_CLIENT_SECRET=""

# Next Auth Email Provider
# smtp://username:password@smtp.example.com:587
EMAIL_SERVER="smtp://resend:api-key@smtp.resend.com:587"
# noreply@example.com
EMAIL_FROM="Vortex <no-reply@cloud>"

# Redis
REDIS_URL="redis://vortex-redis:6379"
REDIS_USERNAME="vortex-main"
REDIS_PASSWORD="147258369"
REDIS_DB="0"
# This should accessible by the agent node
# AGENT_REDIS_URL=""

# Server
SERVER_URL="https://域名"
AGENT_SHELL_URL="https://域名"
JOB_ENABLED=true

# Payment
## DePay https://depay.com
# DEPAY_INTEGRATION_ID=""
# DEPAY_PUBLIC_KEY=""

# Umami https://umami.is/docs
#NEXT_PUBLIC_UMAMI_URL
# script.js
#NEXT_PUBLIC_UMAMI
# website id
#NEXT_PUBLIC_UMAMI_ID
>
docker-compose.yml 未做修改

**Comment by jarvis2f** [comment]
EMAIL_FROM 改成有效的你自己域名邮箱

**Comment by lin1123** [comment]
> EMAIL_FROM 改成有效的你自己域名邮箱

改了，可以正常发送邮件了。

NEXTAUTH_URL="http://localhost:3000"
SERVER_URL="http://localhost:3000"
AGENT_SHELL_URL="http://localhost:3000"
请问这3个地方的域名应该怎么修改，如何直接按env内的默认环境变量，会跳转到本地回环地址，直接改为`http://我的域名`会提示证书问题。

**Comment by jarvis2f** [comment]
AGENT_SHELL_URL 是 下载脚本的地址。其它两个都一样就好了。加上证书吧。

**Comment by lin1123** [comment]
> AGENT_SHELL_URL 是 下载脚本的地址。其它两个都一样就好了。加上证书吧。

证书问题我是用caddy 反代18000端口解决的，添加服务器后，在被控机上执行安装命令会报错
`./vortex.sh: 1: Syntax error: redirection unexpected`

**Comment by jarvis2f** [comment]
sudo bash ./vortex.sh
试试

**Comment by lin1123** [comment]
> sudo bash ./vortex.sh 试试

脚本的内容下载不下来，命令没反应
