### ISSUE TITLE
转发无法连通

### ISSUE THREAD

**Issue by Gin8527** [jarvis2f/vortex#6]
多次安装后设置转发都无法使用，请问应该从哪方面排查问题？vps防火墙都已经关闭，也已尝试多台vps
![image](https://github.com/jarvis2f/vortex/assets/119291050/e8130d8e-317d-43f0-8e0b-c7257407e002)

**Comment by Gin8527** [comment]
启动服务(2024/04/03 08:49:52)...
D:\Program Files\V2rayN\zz_v2rayN-With-Core-SelfContained\guiConfigs\configSpeedtest.json
Xray 1.8.6 (Xray, Penetrates Everything.) Custom (go1.21.4 windows/amd64)
A unified platform for anti-censorship.
2024/04/03 08:49:52 [Info] infra/conf/serial: Reading config: configSpeedtest.json
2024/04/03 08:49:52 [Warning] core: Xray 1.8.6 started
2024/04/03 08:49:53 127.0.0.1:11378 accepted //www.google.com:443 [http10912 -> proxy10912]
2024/04/03 08:49:56 [Warning] [1132116854] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://*.*.*.102:34947/hgjj):  > read tcp *.*.*.52:11379->*.*.*.102:34947: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://*.*.*.102:34947/hgjj):  > read tcp *.*.*.52:11380->*.*.*.102:34947: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://*.*.*.102:34947/hgjj):  > read tcp *.*.*.52:11381->*.*.*.102:34947: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://*.*.*.102:34947/hgjj):  > read tcp *.*.*.52:11382->*.*.*.102:34947: wsarecv: An existing connection was forcibly closed by the remote host. transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://*.*.*.102:34947/hgjj):  > read tcp *.*.*.52:11383->*.*.*.102:34947: wsarecv: An existing connection was forcibly closed by the remote host.] > common/retry: all retry attempts failed
2024/04/03 08:49:58 127.0.0.1:11385 accepted //www.google.com:443 [http -> proxy]

**Comment by jarvis2f** [comment]
使用gost吗？检查一下gost的日志

**Comment by Gin8527** [comment]
是使用gost，转发选项只有一个gost

-- Journal begins at Tue 2023-04-25 01:20:20 CST. --
Apr 03 10:19:07 Pepsi-JP gost[215180]: {"handler":"relay","kind":"service","level":"error","listener":"tcp","msg":"bad version","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:07.017+08:00"}
Apr 03 10:19:07 Pepsi-JP gost[215180]: {"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"...102:34947","msg":"....122:3721 <> ...102:34947","remote":"....122:3721","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:07.416+08:00"}
Apr 03 10:19:07 Pepsi-JP gost[215180]: {"duration":1032239,"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"...102:34947","msg":"....122:3721 >< ...102:34947","remote":"....122:3721","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:07.417+08:00"}
Apr 03 10:19:07 Pepsi-JP gost[215180]: {"handler":"relay","kind":"service","level":"error","listener":"tcp","msg":"bad version","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:07.417+08:00"}
Apr 03 10:19:08 Pepsi-JP gost[215180]: {"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"....102:34947","msg":"....122:3724 <> ....102:34947","remote":"....122:3724","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:08.002+08:00"}
Apr 03 10:19:08 Pepsi-JP gost[215180]: {"duration":392350,"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"...102:34947","msg":"....122:3724 ><...102:34947","remote":"....122:3724","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:08.003+08:00"}
Apr 03 10:19:08 Pepsi-JP gost[215180]: {"handler":"relay","kind":"service","level":"error","listener":"tcp","msg":"bad version","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:08.003+08:00"}
Apr 03 10:19:08 Pepsi-JP gost[215180]: {"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"....102:34947","msg":"....122:3726 <> ...102:34947","remote":"....122:3726","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:08.783+08:00"}
Apr 03 10:19:08 Pepsi-JP gost[215180]: {"duration":243757,"handler":"relay","kind":"handler","level":"info","listener":"tcp","local":"5.34.222.102:34947","msg":"....122:3726 >< ...102:34947","remote":"....122:3726","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:08.783+08:00"}
Apr 03 10:19:08 Pepsi-JP gost[215180]: {"handler":"relay","kind":"service","level":"error","listener":"tcp","msg":"bad version","service":"forward-cluiidemj000dzz75n6fueenj","time":"2024-04-03T10:19:08.783+08:00"}

**Comment by jarvis2f** [comment]
直接使用gost转发试试呢？

**Comment by Gin8527** [comment]
直接安装gost，用gost -L tcp://:9527/落地机ip:端口
这样是可以正常转发的

**Comment by Gin8527** [comment]
又重装了一遍，出现了新问题，服务器的信息无法读取
![image](https://github.com/jarvis2f/vortex/assets/119291050/80de493e-e40d-484e-885c-43174cf7bf80)

**Comment by jarvis2f** [comment]
检查gost配置文件看看。这个信息有延迟存在的。
